config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "reddit/callback", to: "sessions#create"
  delete "sessions", to: "sessions#destroy"
  get "subreddits", to: "subreddits#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post
  attr_accessor :title, :url, :score
  def initialize(attributes)
    @title = attributes[:title]
    @url = attributes[:url]
    @score = attributes[:score]
  end

  def self.set_all_post_attributes(subreddit_title, user)
    posts = RedditService.get_hot_posts(subreddit_title, user)
    posts.map do |post|
      new(title: post[:data][:title], url: post[:data][:url], score: post[:data][:score])
    end
  end
end

app/models/subreddit.rb
class Subreddit
  attr_accessor :title, :subscriber_count, :description, :posts
  def initialize(attributes)
    @title = attributes[:title]
    @subscriber_count = attributes[:subscriber_count]
    @description = attributes[:description]
    @posts = attributes[:posts]
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :username, :karma, :subreddits

  def set_attributes
    attributes = RedditService.get_attributes(self)
    self.username = attributes[:name]
    self.karma = attributes[:link_karma] + attributes[:comment_karma]
    subreddits = RedditService.get_subscribed_subreddits(self)
    self.subreddits = []
    subreddits.each do |subreddit|
      self.subreddits << Subreddit.new(title: subreddit[:data][:title],
                                       subscriber_count: subreddit[:data][:subscribers],
                                       description: subreddit[:data][:description])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      user = User.find(session[:user_id])
      user.set_attributes
      user
    else
      nil
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @current_user = current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    connection = Faraday.new(url: 'https://www.reddit.com/api/v1/access_token')
    connection.basic_auth(ENV['client_id'], ENV['client_secret'])
    response = connection.post("https://www.reddit.com/api/v1/access_token",
                               :grant_type => "authorization_code",
                               :code => params[:code],
                               :redirect_uri => "http://localhost:3000/reddit/callback/")
    response_json = JSON.parse(response.body)
    access_token = response_json["access_token"]
    user = User.find_or_create_by(access_token: access_token)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  def show
    @subreddit_title = params[:title]
    @subscriber_count = params[:subscriber_count]
    @description = params[:description]
    user = current_user
    @posts = Post.set_all_post_attributes(@subreddit_title, user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConsumingRedditApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if @current_user %>
  <div class="subscribed-subreddits">
    <% @current_user.subreddits.each do |subreddit| %>
      <%= link_to subreddit.title, "/subreddits?title=#{subreddit.title}&subscriber_count=#{subreddit.subscriber_count}&description=#{subreddit.description}" %>
    <% end %>
  </div>
  <div class="username">
    <%= @current_user.username %>
    <span class="karma"> (<%= @current_user.karma %>)</span>
  </div>
  <div class="inbox"></div>
  <%= link_to "Logout", sessions_path, class: "logout", method: :delete %>
<% else %>
  <%= link_to "Login", "https://www.reddit.com/api/v1/authorize?client_id=#{ENV['client_id']}&response_type=code&state=1234&redirect_uri=http://localhost:3000/reddit/callback/&duration=temporary&scope=identity,mysubreddits,read", class: "login" %>
<% end %>

app/views/subreddits/show.html.erb
<div class="subreddit-title"><%= @subreddit_title %></div>
<div class="subscriber-count"><%= @subscriber_count %> readers</div>
<div class="description"><%= @description %></div>
<div class="posts">
  <% @posts.each do |post| %>
    <div class="post">
    <%= link_to post.title, post.url %>
    <span class="score"><%= post.score %></span>
    </div>
  <% end %>
</div>